### ISSUE TITLE
picpick@7.2.5: decompress error

### ISSUE THREAD

**Issue by tan-wei** [ScoopInstaller/Extras#12343] opened 2023-11-27 04:04 UTC
```console
Updating 'picpick' (7.2.3 -> 7.2.5)
Downloading new version
picpick_portable.zip (13.8 KB) [======================================================================================================================================================================================================] 100%
Checking hash of picpick_portable.zip ... ok.
Uninstalling 'picpick' (7.2.3)
Unlinking ~\scoop\apps\picpick\current
Installing 'picpick' (7.2.5) [64bit] from extras bucket
Loading picpick_portable.zip from cache
Extracting picpick_portable.zip ... ERROR Exit code was 2!
Failed to extract files from C:\Users\Winterreise\scoop\apps\picpick\7.2.5\picpick_portable.zip.
Log file:
  ~\scoop\apps\picpick\7.2.5\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=picpick%407.2.5%3a+decompress+error
```

Here is 7zip.log:
[7zip.log](https://github.com/ScoopInstaller/Extras/files/13469576/7zip.log)

**Comment by HUMORCE** [comment] 2023-11-28 18:04
Duplicate of #12287

**Closed by HUMORCE** 2023-11-28 18:04 UTC
