### ISSUE TITLE
notepadplusplus@8.1.9: download via aria2 failed

### ISSUE THREAD

**Issue by wrightg42** [ScoopInstaller/Extras#7330] opened 2021-11-14 15:19 UTC
ERROR Download failed! (Error 3) Resource was not found
ERROR https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.1.9/npp.8.1.9.portable.x64.zip
    referer=https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.1.9/
    dir=D:\Scoop\cache
    out=notepadplusplus#8.1.9#https_github.com_notepad-plus-plus_notepad-plus-plus_releases_download_v8.1.9_npp.8.1.9.portable.x64.zip

ERROR & 'D:\Scoop\apps\aria2\current\aria2c.exe' --input-file='D:\Scoop\cache\notepadplusplus.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=18180 --continue --summary-interval 0

**Comment by rashil2000** [comment] 2021-11-14 15:57
Looks like there was a regression in 8.1.9. Can you make a PR for the version bump?

**Comment by issaclin32** [comment] 2021-11-15 07:28
Fixed in https://github.com/ScoopInstaller/Extras/commit/79b5343cd351b60a9d4964c6c98d498a576e169f.

Normally this should be fixed by automatic version updates. However the Excavator bot is now frequently blocked due to *too many requests*.

**Closed by issaclin32** 2021-11-15 07:28 UTC
Labels: package-fix-needed, help-wanted, verified
