### ISSUE TITLE
typora@0.11.16: hash check failed

### ISSUE THREAD

**Issue by seulG** [ScoopInstaller/Extras#7266] opened 2021-11-07 16:55 UTC
the new hash is f1eedc9cc89f8751d4bb77f603f5dabc26364d58116c211fe65ce002dc40be60

**Comment by pratikpc** [comment] 2021-11-07 16:57
Duplicate of https://github.com/ScoopInstaller/Extras/issues/7262

**Closed** 2021-11-07 16:57 UTC
Labels: hash-fix-needed, verified

**Comment by seulG** [comment] 2021-11-07 17:02
thank for you help
