### ISSUE TITLE
gcloud@367.0.0: decompress error

### ISSUE THREAD

**Issue by themrhead** [ScoopInstaller/Extras#7580] opened 2021-12-22 14:01 UTC
#### Scoop Configuration

```json
{
  "lastupdate": "2021-12-22T10:43:43.0592199-03:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by rashil2000** [comment] 2021-12-22 14:20
Duplicate of #7425

**Closed by rashil2000** 2021-12-22 14:20 UTC
