### ISSUE TITLE
[Bug]: mobaxterm settings are deleted when updating the app

### ISSUE THREAD

**Issue by advait404** [ScoopInstaller/Extras#12229] opened 2023-11-14 07:38 UTC
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

mobaxterm

### Expected/Current Behaviour

The MobaXterm.ini file has the settings for the app. After updating the app to the latest version and removing the old version of the app, the settings were deleted along with the old app. 
I think ideally the settings should be in the persist folder to be independent of the app version. 
I used an old backup of the .ini file, added it to the new app version, and everything is restored and works as intended.

### Steps to Reproduce

```console
scoop bucket add extras
scoop install extras/mobaxterm
# not sure how to show the old and new version difference.
```

### Possible Solution

persist folder has a MobaXterm.ini file, but its not used by the app. maybe a file link is missing. ideally this should be created and connected with the app.

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
de70a8f41 (HEAD -> master, origin/master, origin/HEAD) resource-hacker: Update to version 5.2.5

'games' bucket:
184f1ad44 (HEAD -> master, origin/master, origin/HEAD) pcsx2-dev: Update to version 1.7.5203

'java' bucket:
00fb23c2 (HEAD -> master, origin/master, origin/HEAD) openjdk22: Update to version 22-23-ea


'ltguillaume_schep' bucket:
a3926a5 (HEAD -> main, origin/main, origin/HEAD) librewolf: Update to version 119.0.1-1

'main' bucket:
39213f08f (HEAD -> master, origin/master, origin/HEAD) supabase: Update to version 1.112.0

'mo-san_scoop-bucket' bucket:
00c8061 (HEAD -> main, origin/main, origin/HEAD) sysmon: Update to version 15.11

'nerd-fonts' bucket:
bef9b8d (HEAD -> master, origin/master, origin/HEAD) Monaspace: Fix uninstaller script

'nirsoft' bucket:
088d199 (HEAD -> master, origin/master, origin/HEAD) Updated TcpLogView

'nonportable' bucket:
a9d56ee (HEAD -> master, origin/master, origin/HEAD) sql-server-management-studio-np: Update to version 19.2.56.2

'sysinternals' bucket:
7d4955b (HEAD -> main, origin/main, origin/HEAD) sysmon: Update to version 15.11

'versions' bucket:
e24f71efc (HEAD -> master, origin/master, origin/HEAD) vim-tux: Update to version 9.0.2103
```

### Scoop Config

```console
last_update           scoop_branch scoop_repo
-----------           ------------ ----------
11/14/2023 1:56:29 PM master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by davidxuang** [comment] 2023-11-29 02:53
The problem is that the app update the config ini and backup zip by deleting and creating instead of overwriting. There might be a work around to compare timestamps when uninstalling and keep the new files in the persist.

**Comment by advait404** [comment] 2023-12-05 03:06
Updated to version 23.5, and all the old settings persist in the new version.

**Comment by HUMORCE** [comment] 2023-12-05 13:05
> Updated to version 23.5, and all the old settings persist in the new version.

With [the changes](https://github.com/ScoopInstaller/Extras/pull/12364) or not?

**Comment by HUMORCE** [comment] 2023-12-05 23:03
Application are working fine again without any changes to manifest? If so, please close the issue after confirming.

**Comment by advait404** [comment] 2023-12-06 01:04
I tried the following, without any manifest changes:

1. uninstalled mobaxterm and removed files from persist
2. installed mobaxterm@23.4
3. imported a backup configuration from the GUI
4. uninstalled mobaxterm@23.4 (using 'scoop update mobaxterm' did not update to latest version)
5. installed mobaxterm latest version, and it has the latest versions.
 
I am not sure if this is the correct way to test it, since the app is not updating using scoop update.

**Comment by davidxuang** [comment] 2023-12-06 04:13
> following

Use `-f` to force a update. Plus you need to made some modifications before update to mess with the config.

**Closed** 2023-12-07 20:44 UTC
Labels: bug, waiting feedback

**Comment by HUMORCE** [comment] 2023-12-07 20:46
iam not sure if you pulled the change to locally for test or not, but I merged it now.
