### ISSUE TITLE
picpick@7.2.5: decompress error

### ISSUE THREAD

**Issue by themrhead** [ScoopInstaller/Extras#12354] opened 2023-11-27 15:03 UTC
❯ scoop update; scoop cache rm picpick;
Updating Scoop...
Updating 'extras' bucket...
Updating 'java' bucket...
Updating 'main' bucket...
Updating 'nerd-fonts' bucket...
Scoop was updated successfully!
Deleted: 0 files, 0 B

❯ scoop install picpick
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'picpick' (7.2.5) [64bit] from extras bucket
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 067286|OK  |   2.2MiB/s|D:/scoop/cache/picpick#7.2.5#https_www.picpick.org_releases_7.2.5_picpick_portable.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of picpick_portable.zip ... ok.
Extracting picpick_portable.zip ... ERROR Exit code was 2!
Failed to extract files from D:\scoop\apps\picpick\7.2.5\picpick_portable.zip.
Log file:
  D:\scoop\apps\picpick\7.2.5\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=picpick%407.2.5%3a+decompress+error

**Comment by HUMORCE** [comment] 2023-11-28 18:04
Duplicate of #12287

**Closed by HUMORCE** 2023-11-28 18:04 UTC
