### ISSUE TITLE
qalculate@4.8.1: File doesn't exist error

### ISSUE THREAD

**Issue by naderi** [ScoopInstaller/Extras#11906] opened 2023-09-19 08:45 UTC
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

qalculate

### Expected/Current Behaviour

Can't shim 'qalculate-gtk.exe': File doesn't exist.

### Steps to Reproduce

```console
Updating 'qalculate' (4.8.0 -> 4.8.1)
Downloading new version
Loading qalculate-4.8.1-x64.zip from cache.
Checking hash of qalculate-4.8.1-x64.zip ... ok.
Uninstalling 'qalculate' (4.8.0)
Removing shim 'qalc.shim'.
Removing shim 'qalc.exe'.
Unlinking C:\scoop\apps\qalculate\current
Installing 'qalculate' (4.8.1) [64bit] from extras bucket
Loading qalculate-4.8.1-x64.zip from cache.
Extracting qalculate-4.8.1-x64.zip ... done.
Linking C:\scoop\apps\qalculate\current => D:\apps\scoop\apps\qalculate\4.8.1
Creating shim for 'qalc'.
Creating shim for 'qalculate-gtk'.
Can't shim 'qalculate-gtk.exe': File doesn't exist.
```

### Possible Solution

Replace all the “qalculate-gtk.exe” with “qalculate.exe” within manifest.

### Scoop and Buckets Version

```console
'extras' bucket:
eee7624be (HEAD -> master, origin/master, origin/HEAD) sidekick-browser: Update to version 114.51.2.35547-fb3b8c7
```

### Scoop Config

```console
aria2-enabled         : True
alias                 :
last_update           : 19.09.2023 10:31:07
use_lessmsi           : True
aria2-warning-enabled : True
scoop_repo            : https://github.com/lukesampson/scoop
scoop_branch          : master
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by CmdrFirewalker** [comment] 2023-10-13 20:56
I'm confused.
The last commit for the manifest changed it (back?) from qalculate-gtk.exe to qalculate.exe.
Meanwhile all the portable zip-files I can download from qalculate.github.io still contain qalculate-gtk.exe, as does the file in my scoop cache folder.
And yet there are currently open issues that appear to have the opposite problem (https://github.com/ScoopInstaller/Extras/issues/11924 is a duplicate of this).
A couple of weeks ago I manually changed the manifest-file but that mucked with the update process.

**Closed** 2023-11-28 17:00 UTC
Labels: bug
