### ISSUE TITLE
[Bug]: Imageglass package's the naming rule have change.

### ISSUE THREAD

**Issue by CronusLM** [ScoopInstaller/Extras#12339] opened 2023-11-27 01:18 UTC
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

imageglass

### Expected/Current Behaviour

Imageglass package's the naming rule have change.The download link for the latest version of imageglass is https://github.com/d2phap/ImageGlass/releases/download/9.0.7.1125/ImageGlass_9.0.7.1125_x64.zip

### Steps to Reproduce

```console
PS C:\Users\Kronus> scoop update imageglass
imageglass: 8.10.9.27 -> 9.0.7.1125
Updating one outdated app:
Updating 'imageglass' (8.10.9.27 -> 9.0.7.1125)
Downloading new version
远程服务器返回错误: (404) 未找到。
所在位置 C:\Scoop\apps\scoop\current\lib\install.ps1:111 字符: 9
+         throw $e
+         ~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], WebException
    + FullyQualifiedErrorId : 远程服务器返回错误: (404) 未找到。
```

### Possible Solution

Fix download links and autoupdate

### Scoop and Buckets Version

```console
PS C:\Users\Kronus> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
8f54a2771 (HEAD -> master, origin/master, origin/HEAD) sidekick-browser: Update to version 114.52.2.36023-3b20c98

'java' bucket:
7c851157 (HEAD -> master, origin/master, origin/HEAD) temurin11-nightly-jre: Update to version 11.0.22-4.0.202311251716

'main' bucket:
170298a04 (HEAD -> master, origin/master, origin/HEAD) ripgrep: Update to version 14.0.1

'nonportable' bucket:
c68348e (HEAD -> master, origin/master, origin/HEAD) 10x-np: Update to version 1.0.101

'scoopet' bucket:
25185d7 (HEAD -> master, origin/master, origin/HEAD) umi-ocr: update

'test' bucket:
f6fb36c (HEAD -> master, origin/master, origin/HEAD) Update umi-ocr-test.json
```

### Scoop Config

```console
PS C:\Users\Kronus> scoop config


root_path             : C:\Scoop
global_path           : C:\Program Files
last_update           : 2023-11-27T08:51:49.1758045+08:00
aria2-enabled         : False
aria2-warning-enabled : False
scoop_branch          : master
scoop_repo            : https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
PS C:\Users\Kronus> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22621.2506
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2506
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by rouvwhqk** [comment] 2023-11-27 02:18
![Uploading Snipaste_2023-11-27_10-17-22.png…]()

**Comment by rouvwhqk** [comment] 2023-11-27 02:20
I have the same problem.
![Snipaste_2023-11-27_10-17-22](https://github.com/ScoopInstaller/Extras/assets/59132399/cd05fa77-440b-442a-8223-0ce2b7059de9)

**Comment by Uranite** [comment] 2023-11-27 05:39
Duplicate of #12313

**Comment by HUMORCE** [comment] 2023-11-28 18:02
#12319

**Closed by HUMORCE** 2023-11-28 18:02 UTC
Labels: bug
