### ISSUE TITLE
avidemux@2.8.1: decompress error

### ISSUE THREAD

**Issue by f-malta** [ScoopInstaller/Extras#10409] opened 2023-02-02 16:35 UTC
Installing 'avidemux' (2.8.1) [64bit] from extras bucket
Avidemux_2.8.1.VC++.64bits.exe (38,1 MB) [====================================================================] 100%
Checking hash of Avidemux_2.8.1.VC++.64bits.exe ... ok.
Extracting dl.7z ... ERROR Exit code was 2!
Failed to extract files from C:\Users\femao\scoop\apps\avidemux\2.8.1\dl.7z.
Log file:
  ~\scoop\apps\avidemux\2.8.1\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=avidemux%402.8.1%3a+decompress+error

**Comment by HUMORCE** [comment] 2023-02-03 15:47
Duplicate of #9689

**Closed by HUMORCE** 2023-02-03 15:47 UTC
