### ISSUE TITLE
avidemux@2.8.1: decompress error

### ISSUE THREAD

**Issue by flyperic** [ScoopInstaller/Extras#10130] opened 2022-12-28 18:09 UTC
Hi, I tried to install avidemux and encounter this issue :
---
C:\WINDOWS\system32>scoop install avidemux
WARN  Purging previous failed installation of avidemux.
ERROR 'avidemux' isn't installed correctly.
Removing older version (2.8.1).
'avidemux' was uninstalled.
Installing 'avidemux' (2.8.1) [64bit] from extras bucket
Loading Avidemux_2.8.1.VC++.64bits.exe from cache
Checking hash of Avidemux_2.8.1.VC++.64bits.exe ... ok.
Extracting dl.7z ... ERROR Exit code was 2!
Failed to extract files from D:\APPS\Scoop\root\apps\avidemux\2.8.1\dl.7z.
Log file:
  D:\APPS\Scoop\root\apps\avidemux\2.8.1\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=avidemux%402.8.1%3a+decompress+error
--- 
Also :
D:\APPS\Scoop\root\apps\avidemux\2.8.1\dl.7z cannot be opened manually with 7-zip neither.
Error message is "Is not archive".

**Comment by HUMORCE** [comment] 2022-12-28 18:19
Duplicate of #9689

**Closed by HUMORCE** 2022-12-28 18:19 UTC
