### ISSUE TITLE
avidemux@2.8.1: decompress error

### ISSUE THREAD

**Issue by mesmariusz** [ScoopInstaller/Extras#9689] opened 2022-11-08 17:49 UTC
Hi, 
I've got an issue regarding the installation of avidemux:

![image](https://user-images.githubusercontent.com/3919173/200638293-97e3f439-8df9-4a7e-90ef-44fd3c5e6eab.png)

#### Scoop Configuration

```json
{
    "last_update":  "2022-11-08T17:45:46.3258362+01:00",
    "scoop_branch":  "master",
    "scoop_repo":  "https://github.com/ScoopInstaller/Scoop"
}

```

**Comment by niheaven** [comment] 2022-11-09 09:31
Please attach your `7zip.log`, thanks.

**Comment by tech189** [comment] 2022-11-09 10:50
Unfortunately they changed the packaging of the latest release to a Qt based installer. See Universal Extractor's output here:
```
Qt Installer  v2.0.0 - 3.0.x - 2018.12.11 - www.qt.io  - stub : Microsoft Visual C++ v.12 - 2013 ( E8 MZ-PE ) www.microsoft.com [ .QT METADATA Section 4 ] - no sec. CAB/7z/Zip [ Win Vista ] , 
Overlay :  -> .rcc file - Qt Resources ( Binary Data ) - http://qt-project.org
```

It seems there's currently no way to extract this type of installer silently. Apparently it's some sort of .zlib compression but I couldn't find a zlib extractor that worked. Chocolatey does it by providing [a `.qs` script](https://github.com/chocolatey-community/chocolatey-packages/blob/master/automatic/avidemux/tools/avidemux.qs) with `--script` parameter that presses the buttons automatically but it still will pop up a window. And, that will ask for admin rights to install it to C:\Program Files.

I think we might have to move it to the [nonportable bucket](https://github.com/ScoopInstaller/Nonportable).

In the meantime you could install the nightly version `avidemux-nightly` from the versions bucket.

**Comment by pbb72** [comment] 2022-12-14 11:06
Duplicate of #9496.

**Comment by sedlund** [comment] 2023-02-20 01:41
maybe this should be disabled until it is fixed?

**Closed** 2023-05-30 21:40 UTC
Labels: upstream

**Comment by HUMORCE** [comment] 2023-05-30 21:42
It should be fixed now.
