### ISSUE TITLE
[Request]: VeraCrypt

### ISSUE THREAD

**Issue by Zcooger** [ScoopInstaller/Extras#10728] opened 2023-03-11 09:31 UTC
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

veracrypt

### Description

File(system) encryption software - TrueCrypt successor

### Homepage

https://veracrypt.fr/en/Home.html

### Download Link(s)

https://sourceforge.net/projects/veracrypt/files/

### Some Indication of Popularity/Repute

Open source disk encryption with strong security for the Paranoid - https://en.wikipedia.org/wiki/VeraCrypt#References

**Comment by aliesbelik** [comment] 2024-01-22 01:43
Duplicate of #2381.

**Closed by aliesbelik** 2024-01-22 01:43 UTC
Labels: duplicate, package-request
