### ISSUE TITLE
avidemux@2.8.1: decompress error

### ISSUE THREAD

**Issue by ProxyVT** [ScoopInstaller/Extras#10187] opened 2023-01-05 15:44 UTC
```
Installing 'avidemux' (2.8.1) [64bit] from extras bucket
Loading Avidemux_2.8.1.VC++.64bits.exe from cache
Checking hash of Avidemux_2.8.1.VC++.64bits.exe ... ok.
Extracting dl.7z ... ERROR Exit code was 2!
Failed to extract files from C:\Users\Umka\scoop\apps\avidemux\2.8.1\dl.7z.
Log file:
  ~\scoop\apps\avidemux\2.8.1\7zip.log
```
[7zip.log](https://github.com/ScoopInstaller/Extras/files/10353479/7zip.log)

**Comment by tech189** [comment] 2023-01-05 22:44
Duplicate of #9689

**Closed by tech189** 2023-01-05 22:44 UTC
