### ISSUE TITLE
Cannot update beacuse of the local changes that shouldn't be existed.

### ISSUE THREAD

**Issue by lijian12345** [ScoopInstaller/Extras#7661] opened 2022-01-03 16:15 UTC
Run scoop update and the output is as following:
```
Updating 'extras' bucket...
error: Your local changes to the following files would be overwritten by merge:
        scripts/everything/install-context.reg
        scripts/everything/uninstall-context.reg
Please commit your changes or stash them before you merge.
Aborting
```

And these changes can't be discarded.

**Comment by rashil2000** [comment] 2022-01-03 16:21
Do this:

```
git rm .gitattributes
git add -A
git reset --hard
```

Duplicate of #7546

**Closed by rashil2000** 2022-01-03 16:21 UTC
Labels: bug
