### ISSUE TITLE
[Bug]: tor-browser installer script fails: Could not find 'Browser'! (error 16)

### ISSUE THREAD

**Issue by tdworz** [ScoopInstaller/Extras#11183] opened 2023-04-30 15:26 UTC
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

tor-browser

### Expected/Current Behaviour

I expect tor-browser to install normally. Instead, the installation of `tor-browser` is failing and giving error 16.

### Steps to Reproduce

```console
PS C:\Users\X> scoop install tor-browser
Installing 'tor-browser' (12.0.4) [64bit] from extras bucket
torbrowser-install-win64-12.0.4_ALL.exe (91.5 MB) [===========================================================] 100%
Checking hash of torbrowser-install-win64-12.0.4_ALL.exe ... ok.
Running installer script...
Could not find 'Browser'! (error 16)
At C:\Users\X\scoop\apps\scoop\current\lib\core.ps1:638 char:9
+         throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find 'Browser'! (error 16):String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find 'Browser'! (error 16)
```

### Possible Solution

I found another bug #11086 giving error 16 but I am not sure how to relate the solutions to this bug.

### Scoop and Buckets Version

```console
PS C:\Users\X> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
18051a8dd (HEAD -> master, origin/master, origin/HEAD) snappy-driver-installer-origin: Remove `extract_dir` (#11182)
```

### Scoop Config

```console
PS C:\Users\X> scoop config

last_update
-----------
2023-04-30T09:15:37.5349645-05:00
```

### PowerShell Version

```console
PS C:\Users\X> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22621.963
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.963
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by HUMORCE** [comment] 2023-04-30 16:33
Cannot reproduce. but I make a PR for improve installation of the app, please retry when merged.

```
'extras' bucket:
18051a8dd (HEAD -> master, origin/master, origin/HEAD) snappy-driver-installer-origin: Remove `extract_dir` (#11182)

extras on  master
❯ scoop install extras/tor-browser
Installing 'tor-browser' (12.0.4) [64bit] from extras bucket
Loading torbrowser-install-win64-12.0.4_ALL.exe from cache
Checking hash of torbrowser-install-win64-12.0.4_ALL.exe ... ok.
Running installer script...
Linking ~\scoop\apps\tor-browser\current => ~\scoop\apps\tor-browser\12.0.4
Creating shim for 'tor-browser'.
Creating shortcut for Tor Browser (firefox.exe)
Persisting TorBrowser\Data\Browser\profile.default
Persisting TorBrowser\Data\Tor
'tor-browser' (12.0.4) was installed successfully!
```

**Closed** 2023-04-30 16:33 UTC
Labels: bug

**Comment by tdworz** [comment] 2023-04-30 18:57
@HUMORCE Thanks! Your updates fixed the issue (for whatever reason)!

```
PS C:\Users\X> scoop install tor-browser
WARN  Purging previous failed installation of tor-browser.
ERROR 'tor-browser' isn't installed correctly.
Removing older version (12.0.4).
'tor-browser' was uninstalled.
Installing 'tor-browser' (12.0.4) [64bit] from extras bucket
torbrowser-install-win64-12.0.4_ALL.exe (91.5 MB) [===========================================================] 100%
Checking hash of torbrowser-install-win64-12.0.4_ALL.exe ... ok.
Extracting dl.7z ... done.
Running pre_install script...
Linking ~\scoop\apps\tor-browser\current => ~\scoop\apps\tor-browser\12.0.4
Creating shim for 'tor-browser'.
Creating shortcut for Tor Browser (firefox.exe)
Persisting TorBrowser\Data\Browser\profile.default
Persisting TorBrowser\Data\Tor
'tor-browser' (12.0.4) was installed successfully!
```
