### ISSUE TITLE
[Request] Add protonvpn

### ISSUE THREAD

**Issue by dtantono** [ScoopInstaller/Extras#7114] opened 2021-10-28 10:17 UTC
PackageIdentifier: protonvpn
PackageVersion: 1.20.4
PackageLocale: en-US
Publisher: Protonvpn
PackageName: protonvpn
License: open source
ShortDescription: vpn service provider
Installers:

Architecture: x64
InstallerType: exe
InstallerUrl: https://github.com/ProtonVPN/win-app/releases/download/1.20.4/ProtonVPN_win_v1.20.4.exe
ManifestType: singleton
ManifestVersion: 1.0.0

**Comment by nagromc** [comment] 2022-06-08 07:59
Duplicate of #4678

**Closed** 2022-06-08 09:08 UTC
Labels: help-wanted, package-request
