### ISSUE TITLE
docker-desktop

### ISSUE THREAD

**Issue by dong-lufei** [ScoopInstaller/Extras#11000] opened 2023-04-11 10:00 UTC
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [ ] Full version (i.e. not a trial version)
- [ ] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

docker-desktop

### Description

docker's desktop version

### Homepage

https://docs.docker.com/desktop/release-notes/

### Download Link(s)

https://docs.docker.com/desktop/release-notes/

### Some Indication of Popularity/Repute

docker

**Comment by HUMORCE** [comment] 2023-04-11 23:24
Duplicate of #2594

**Closed by HUMORCE** 2023-04-11 23:24 UTC
Labels: package-request
