### ISSUE TITLE
[Bug]: calibre@6.26.0 The default install path is too long, exceeding 59 characters.

### ISSUE THREAD

**Issue by gotnix** [ScoopInstaller/Extras#11872] opened 2023-09-10 15:23 UTC
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

calibre

### Expected/Current Behaviour

I hope to install Calibre silently, but now I need to manually select the installation path.

### Steps to Reproduce

```console
PS C:\Users\zhengpf> scoop install calibre
Installing 'calibre' (6.26.0) [64bit] from extras bucket
Loading calibre-portable-installer-6.26.0.exe from cache
Checking hash of calibre-portable-installer-6.26.0.exe ... ok.
Running installer script...

Get a GUI Error as follow:
Path to Calibre Portable
(C:\Users\zhengpf\scoop\apps\calibre\6.25.0\Calibre Portable) too long. It must be less than 59 characters.
```

### Possible Solution

I have no idea about this issue, because I’m not sure if it’s caused by `scoop` or by the `calibre-portable-installer-6.26.0.exe`.

### Scoop and Buckets Version

```console
PS> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
9ff803128 (HEAD -> master, origin/master, origin/HEAD) qownnotes: Update to version 23.9.2

'java' bucket:
2a0b5d67 (HEAD -> master, origin/master, origin/HEAD) temurin11-nightly-jre: Update to version 11.0.21-6.0.202309091716

'main' bucket:
77166d0a4 (HEAD -> master, origin/master, origin/HEAD) red: Update to version 10sep23
```

### Scoop Config

```console
PS > scoop config

last_update                       scoop_branch scoop_repo
-----------                       ------------ ----------
2023-09-10T22:06:39.9008439+08:00 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
PS > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22621.1778
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.1778
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by HUMORCE** [comment] 2023-09-10 23:01
Duplicate of #11367

**Closed by HUMORCE** 2023-09-10 23:01 UTC
Labels: bug
