### ISSUE TITLE
imageglass@8.6.6.6: Download via aria2 failed

### ISSUE THREAD

**Issue by arichtman** [ScoopInstaller/Extras#8614] opened 2022-06-04 09:28 UTC
I'm happy to work on this I just need some direction on how to do different strings in the download URL that vary per major version. I'm not sure what the most appropriate way is to adjust for that without breaking downloads of other versions.

Release file naming from 8.6.6.6 includes the string "Kobe". It looks like v9 would use the string "Moon"

```Text
ERROR Download failed! (Error 3) Resource was not found
ERROR https://github.com/d2phap/ImageGlass/releases/download/8.6.6.6/ImageGlass_8.6.6.6_x64.zip
    referer=https://github.com/d2phap/ImageGlass/releases/download/8.6.6.6/
    dir=C:\Users\ariel\scoop\cache
    out=imageglass#8.6.6.6#https_github.com_d2phap_ImageGlass_releases_download_8.6.6.6_ImageGlass_8.6.6.6_x64.zip

ERROR & 'C:\Users\ariel\scoop\apps\aria2\1.36.0-1\aria2c.exe' --input-file='C:\Users\ariel\scoop\cache\imageglass.txt' --user-agent='Shovel/1.0 (+https://shovel.ash258.com) PowerShell/5.1 (Windows NT 10.0.19044.0; Win64; x64;)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=26472 --continue --summary-interval 0
ERROR Download failed! (Error 3) Resource was not found

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=imageglass%408.6.6.6%3a+Download+via+aria2+failed&body=Download+failed!+(Error+3)+Resource+was+not+found
ERROR This application failed to update: imageglass
```

![image](https://user-images.githubusercontent.com/10679234/171993424-1bf4f981-5ef1-453b-a698-2cd83c659cb3.png)

**Comment by arichtman** [comment] 2022-06-04 09:30
#8612 #8611

**Comment by rashil2000** [comment] 2022-06-04 09:57
Duplicate of https://github.com/ScoopInstaller/Extras/issues/8611

**Closed by rashil2000** 2022-06-04 09:57 UTC
Labels: verified, manifest-fix-needed, help wanted
