### ISSUE TITLE
furmark@1.35.0.0: decompress error

### ISSUE THREAD

**Issue by arinoki** [ScoopInstaller/Extras#11479] opened 2023-06-22 18:34 UTC
Extracting FurMark_1.35.0.0_Setup.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Soft\Scoop\apps\furmark\1.35.0.0\FurMark_1.35.0.0_Setup.exe.
Log file:
  C:\Soft\Scoop\apps\furmark\1.35.0.0\innounp.log

The setup files are corrupted or made by incompatible version. Maybe it's not an Inno Setup installation at all.
(00492DAA)

**Comment by sebastien46** [comment] 2023-06-22 20:59
Duplicate of #11476

**Closed** 2023-06-23 03:27 UTC
