### ISSUE TITLE
DoubleCMD not portable

### ISSUE THREAD

**Issue by yoyurec** [ScoopInstaller/Extras#10849] opened 2023-03-26 06:57 UTC
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

doublecmd

### Expected/Current Behaviour

double commander package uses common installation, but this app supports a configurable settings folder (user home / app folder). is it possible to preconfigure (postinstall) to use scoop `persist` folder?

### Steps to Reproduce

```console
* install doublecmd
* check `persist` folder - no settings for app
```

### Possible Solution

some post-install script should edit settings.ini

### Scoop and Buckets Version

```console
latest
```

### Scoop Config

```console
common
```

### PowerShell Version

```console
latest
```

**Comment by HUMORCE** [comment] 2023-04-11 21:30
It's settings stored in `$HOME\appdata\roaming\doublecmd\*`. please provide some info/doc

**Comment by HUMORCE** [comment] 2023-04-11 21:49
> maybe create symlink?

Unrecommended for official buckets.

**Comment by goyalyashpal** [comment] 2024-04-09 20:57
* duplicate of https://github.com/ScoopInstaller/Extras/issues/2181

**Closed** 2024-04-10 10:54 UTC
Labels: bug
