### ISSUE TITLE
avidemux@2.8.1: decompress error

### ISSUE THREAD

**Issue by f-cramer** [ScoopInstaller/Extras#10209] opened 2023-01-09 13:49 UTC
7-Zip 22.01 (x64) : Copyright (c) 1999-2022 Igor Pavlov : 2022-07-15

Scanning the drive for archives:
1 file, 39995334 bytes (39 MiB)

Extracting archive: ~\scoop\apps\avidemux\2.8.1\dl.7z

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
ERROR: ~\scoop\apps\avidemux\2.8.1\dl.7z
~\scoop\apps\avidemux\2.8.1\dl.7z
Open ERROR: Cannot open the file as [7z] archive

ERRORS:
Is not archive

**Comment by HUMORCE** [comment] 2023-01-09 13:58
Duplicate of #9689

**Closed by HUMORCE** 2023-01-09 13:58 UTC

**Comment by f-cramer** [comment] 2023-01-09 14:00
sorry, I only searched for avi instead of the full avidemux ;)
