### ISSUE TITLE
avidemux@2.8.1: decompress error

### ISSUE THREAD

**Issue by dougthebug** [ScoopInstaller/Extras#10291] opened 2023-01-21 18:04 UTC
Scanning the drive for archives:
1 file, 39995334 bytes (39 MiB)

Extracting archive: C:\Users\Baker\scoop\apps\avidemux\2.8.1\dl.7z

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
ERROR: C:\Users\Baker\scoop\apps\avidemux\2.8.1\dl.7z
C:\Users\Baker\scoop\apps\avidemux\2.8.1\dl.7z
Open ERROR: Can not open the file as [7z] archive

ERRORS:
Is not archive

**Comment by HUMORCE** [comment] 2023-01-23 13:11
Duplicate of #9689

**Closed by HUMORCE** 2023-01-23 13:11 UTC
