### ISSUE TITLE
Disable autoupdate for `firefox` and `thunderbird` and set profile

### ISSUE THREAD

**Issue by valentinpi** [ScoopInstaller/Extras#6854] opened 2021-09-13 17:04 UTC
It is quite annoying as updates may install themselves or download but install on your command. I only want scoop to manage my installations.

One can solve this by putting a `distribution` folder with a file `policies.json` inside of the program directories. The file must contain:
```
{
"policies":
   {
     "DisableAppUpdate": true
    }
}
```
I would suggest to put this into the automation.

Also, for people who don't use multiple profiles in these programs it might be useful to have some automation that automatically sets the profile to `default-release` after an update. The only workaround I have right now is to manually start the programs with the profile option:
```
$ firefox -p
$ thunderbird -p
```
After an update and then set the profile manually. It is quite tidious to be aware of these changes every time I update so I suggest there should be automation to launch the progams once after an update. Or some other solution. Although this topic is nothing new, see e.g. #4377 for reference.

**Comment by HUMORCE** [comment] 2021-09-13 23:58
1. https://github.com/lukesampson/scoop-extras/pull/6730
2. firefox-portable

**Comment by valentinpi** [comment] 2021-09-14 15:52
Nice! But is it not possible to persist profiles and then execute some command setting the profiles folder as default for the "normal" `firefox`?

**Comment by HUMORCE** [comment] 2021-09-14 16:35
https://github.com/lukesampson/scoop-extras/blob/818715a7baf2773e01204de027c32e3eb702f45f/bucket/firefox-portable.json#L17-L23
`firefox-portable.json` will break the CLI options on shell/console, so i created this manifest for self-use:
https://github.com/HUMORCE/scoop-nuke/blob/master/bucket/firefox.json
- execute `firefox` on shell just like firefox.json on extras bucket.
- open firefox via the `Firefox` shortcut to use persist profile.
- `Firefox Profile Manager` shortcut = `firefox -P`

**Comment by valentinpi** [comment] 2021-09-14 20:05
That's good but it still does not fix the issue that when you update the application it does not automatically set the last profile.

**Comment by HUMORCE** [comment] 2021-09-14 21:48
no,firefox-portable and my manifest are good for keeping profile.

if using firefox.json, see: https://github.com/mozilla/policy-templates/blob/master/README.md#LegacyProfiles
if switching to firefox-portable.json, manually move the profile directory if need. (see: about:profiles)

|manifest|profiles path|
|-|-|
|firefox.json (extras bucket)|~\AppData\Roaming\|Local\Mozilla\Firefox\Profiles\\<PROFILE_ID>|
|firefox-portable.json (extras bucket)|$env:SCOOP\persist\firefox-portable\profile|

**Comment by candrapersada** [comment] 2021-10-02 08:55
Disable autoupdate for `waterfox`

**Comment by rashil2000** [comment] 2021-12-21 06:43
Duplicate of #4377

**Closed by rashil2000** 2021-12-21 06:43 UTC
Labels: help-wanted, package improvement
