### ISSUE TITLE
[Bug]: flutter depends on "java/temurin8-jdk", but this version of java is not fully compatible! For example "flutter doctor --android-licenses" command fails.  "openjdk17" works perfectly fine. Please update the dependencies. 

### ISSUE THREAD

**Issue by AnshulDevAPI** [ScoopInstaller/Extras#10762] opened 2023-03-14 07:14 UTC
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

flutter

### Expected/Current Behaviour

flutter depends on "java/temurin8-jdk", but this version of java is not fully compatible! For example "flutter doctor --android-licenses" command fails.  "openjdk17" works perfectly fine. Please update the dependencies. 

### Steps to Reproduce

```console
> scoop install flutter
> flutter doctor --android-licenses
```

### Possible Solution

"openjdk17" works perfectly fine. Please update the dependencies. 

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
3bdb4bec1 (HEAD -> master, origin/master, origin/HEAD) speedtest@1.10.163: Fix hash (Closes #10760)

'java' bucket:
8c341dab (HEAD -> master, origin/master, origin/HEAD) openjdk21: Update to version 21-13-ea

'main' bucket:
7e9aa41fe (HEAD -> master, origin/master, origin/HEAD) kustomize: Update to version 5.0.1
```

### Scoop Config

```console
last_update           scoop_branch scoop_repo
-----------           ------------ ----------
3/14/2023 12:30:15 PM master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by HUMORCE** [comment] 2023-03-14 10:22
Duplicate of #10413

**Closed by HUMORCE** 2023-03-14 10:22 UTC
Labels: bug
