### ISSUE TITLE
fiddler@5.0.20211.51073: decompress error

### ISSUE THREAD

**Issue by fchj** [ScoopInstaller/Extras#11471] opened 2023-06-22 06:39 UTC
PS C:\REDACTED> scoop install extras/fiddler
WARN  Purging previous failed installation of fiddler.
ERROR 'fiddler' isn't installed correctly.
Removing older version (5.0.20211.51073).
'fiddler' was uninstalled.
Installing 'fiddler' (5.0.20211.51073) [64bit] from extras bucket
Loading FiddlerSetup.exe from cache
Checking hash of FiddlerSetup.exe ... ok.
Extracting dl.7z ... ERROR Exception calling "Start" with "0" argument(s): "Mappenavnet er ugyldigt"
Failed to extract files from C:\Users\REDACTED\scoop\apps\fiddler\5.0.20211.51073\dl.7z.
Log file:
  ~\scoop\apps\fiddler\5.0.20211.51073\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=fiddler%405.0.20211.51073%3a+decompress+error
PS C:\REDACTED>

**Comment by HUMORCE** [comment] 2023-06-22 12:15
```
PS C:\Users\WDAGUtilityAccount> scoop install extras/fiddler -u
Installing 'fiddler' (5.0.20211.51073) [64bit] from extras bucket
Loading FiddlerSetup.exe from cache
Checking hash of FiddlerSetup.exe ... ok.
Extracting dl.7z ... done.
Running pre_install script...
Linking ~\scoop\apps\fiddler\current => ~\scoop\apps\fiddler\5.0.20211.51073
Creating shim for 'Fiddler'.
Creating shortcut for Fiddler (Fiddler.exe)
Creating shortcut for Fiddler ScriptEditor (FSE2.exe)
Persisting Scripts
'fiddler' (5.0.20211.51073) was installed successfully!
```

Cannot reproduce.

Please provides more information:

- `scoop list 7zip`
- `scoop config`
- `...\7zip.log`, if it's not empty
-

**Comment by StarsbySea** [comment] 2023-07-06 17:41
"Mappenavnet er ugyldigt" is Danish and translates to "The directory name is invalid". It may be that your username contains non-ASCII characters etc. Please consider providing more information as per the reply above.
As this cannot be replicated locally, if you are unable to provide more information, there is nothing we can do, so please consider closing this topic.

**Comment by HUMORCE** [comment] 2023-07-22 10:24
Temporarily closed, feel free to reopen this issue.

**Reasons:**
- Cannot reproduce.
- No response and additional information

**Closed by HUMORCE** 2023-07-22 10:24 UTC
