### ISSUE TITLE
avidemux@2.8.1: decompress error

### ISSUE THREAD

**Issue by pinokaille** [ScoopInstaller/Extras#11351] opened 2023-05-26 18:52 UTC
# CMD OUTPUT 
```Installing 'avidemux' (2.8.1) [64bit] from extras bucket
Avidemux_2.8.1.VC++.64bits.exe (38,1 MB) [====================================================================] 100%
Checking hash of Avidemux_2.8.1.VC++.64bits.exe ... ok.
Extracting dl.7z ... ERROR Exit code was 2!
Failed to extract files from C:\Users\Anthony\scoop\apps\avidemux\2.8.1\dl.7z.
Log file:
  ~\scoop\apps\avidemux\2.8.1\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=avidemux%402.8.1%3a+decompress+error
```

# 7zip.log

```
7-Zip 23.00 (x64) : Copyright (c) 1999-2023 Igor Pavlov : 2023-05-07

Scanning the drive for archives:
1 file, 39995334 bytes (39 MiB)

Extracting archive: C:\Users\Mleb\scoop\apps\avidemux\2.8.1\dl.7z

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
ERROR: C:\Users\Mleb\scoop\apps\avidemux\2.8.1\dl.7z
C:\Users\Mleb\scoop\apps\avidemux\2.8.1\dl.7z
Open ERROR: Cannot open the file as [7z] archive


ERRORS:
Is not archive
```

**Comment by HUMORCE** [comment] 2023-05-27 10:56
Duplicate of #9689

**Closed by HUMORCE** 2023-05-27 10:56 UTC
