### ISSUE TITLE
gimp@2.10.38-1: decompress error

### ISSUE THREAD

**Issue by mgbon2** [ScoopInstaller/Extras#14128] opened 2024-10-03 23:33 UTC
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.

Cleared cache, still occurred.
Disabled aria2, cleared cache, still occurred.

**Comment by patevs** [comment] 2024-10-04 01:13
Duplicate of #14126

**Closed** 2024-10-04 06:43 UTC
Labels: duplicate
