### ISSUE TITLE
[Bug]: Unable to install prusaslicer version 2.5.1

### ISSUE THREAD

**Issue by GotAnAccount** [ScoopInstaller/Extras#10870] opened 2023-03-29 18:24 UTC
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

prusaslicer

### Expected/Current Behaviour

In the processes of installing the package, when scoop is extracting the package, I get an error 16, Could not find 'PrusaSlicer-2.5.1+win64-202303151108'.

Here is the exact result I get:

$ scoop install prusaslicer
Installing 'prusaslicer' (2.5.1) [64bit] from extras bucket
Loading PrusaSlicer-2.5.1+win64-202303151108_signed.zip from cache.
Checking hash of PrusaSlicer-2.5.1+win64-202303151108_signed.zip ... ok.
Extracting PrusaSlicer-2.5.1+win64-202303151108_signed.zip ... Could not find 'PrusaSlicer-2.5.1+win64-202303151108'! (error 16)
Au caractère C:\apps\scoop\apps\scoop\current\lib\core.ps1:638 : 9
+         throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...08'! (error 16):String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find 'PrusaSlicer-2.5.1+win64-202303151108'! (error 16)

### Steps to Reproduce

```console
$ scoop install prusaslicer
```

### Possible Solution

sadly I do not know what the solution can be.

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
fffdc3086 (HEAD -> master, origin/master, origin/HEAD) wxdfast: Update to version 0.70.4

'java' bucket:
62a2b10e (HEAD -> master, origin/master, origin/HEAD) temurin11-nightly-jre: Update to version 11.0.19-6.0.202303281811

'main' bucket:
8a0010efe (HEAD -> master, origin/master, origin/HEAD) vulkan: Update to version 1.3.243.0

'nerd-fonts' bucket:
58f791f (HEAD -> master, origin/master, origin/HEAD) Font-Awesome: Update to version 6.4.0

'nonportable' bucket:
1bbab5d (HEAD -> master, origin/master, origin/HEAD) notepadplusplus-np: Update to version 8.5.1

'versions' bucket:
4609a7a74 (HEAD -> master, origin/master, origin/HEAD) rclone-beta: Update to version 1.63.0-beta.6932.4d7b6e14b
```

### Scoop Config

```console
aria2-warning-enabled : False
virustotal_api_key    : 155f752071aa7884443efe7ad478eafe5ac3a4be7901c064c5b28891d149c6e4
last_update           : 2023-03-29T14:09:50.5432134-04:00
scoop_branch          : master
scoop_repo            : https://github.com/lukesampson/scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22621.963
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.963
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by HUMORCE** [comment] 2023-04-04 11:59
Duplicate of #10889

**Closed by HUMORCE** 2023-04-04 11:59 UTC
Labels: bug
