### ISSUE TITLE
scoop update causes error message "Your local changes to the following files would be overwritten by merge"

### ISSUE THREAD

**Issue by lepicsaintloup** [ScoopInstaller/Extras#7574] opened 2021-12-22 03:15 UTC
## Bug Report

**Package Name:** Scoop

### Current Behaviour

See log below. 

### Expected Behaviour

An error free update

### Additional context/output
```
PS C:\Users\xxxx> scoop update *
Updating Scoop...
Updating 'extras' bucket...
error: Your local changes to the following files would be overwritten by merge:
        scripts/everything/install-context.reg
        scripts/everything/uninstall-context.reg
Please commit your changes or stash them before you merge.
Aborting
```
### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 7.2.1

**Additional software:** Windows terminal

#### Scoop Configuration

```json
{
  "SCOOP_BRANCH": "master",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "lastupdate": "2021-12-22T14:05:35.9687239+11:00"
}

```

**Comment by rashil2000** [comment] 2021-12-22 06:05
Can you do `scoop bucket rm extras` and then `scoop bucket add extras`?

**Comment by rtfcv** [comment] 2021-12-22 07:41
I think this is a duplicate of #7546
the root cause of this is being discussed there as well

**Closed** 2021-12-22 07:47 UTC
Labels: bug
