### ISSUE TITLE
[Request]: Docker Desktop

### ISSUE THREAD

**Issue by anderlli0053** [ScoopInstaller/Extras#10429] opened 2023-02-04 09:10 UTC
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Docker Desktop

### Description

Docker Desktop – the fastest way to containerize applications.

### Homepage

https://www.docker.com/products/docker-desktop/

### Download Link(s)

https://www.docker.com/products/docker-desktop/

### Some Indication of Popularity/Repute

It is pretty much the same popularity/remote as the Docker engine and its CLI (which are already included in the official buckets)

**Comment by HUMORCE** [comment] 2023-02-04 12:31
Duplicate of #2594

**Closed by HUMORCE** 2023-02-04 12:31 UTC
Labels: package-request
