### ISSUE TITLE
Kdenlive: Missing avfilter and avformat mlt module (ffmpeg)

### ISSUE THREAD

**Issue by chrishazfun** [ScoopInstaller/Extras#8968] opened 2022-08-01 16:40 UTC
## Bug Report

**Package Name:** kdenlive

### Current Behavior
I cannot import any content from any source, internal drive, portable drive, anything.

### Expected Behaviour
I import a file (both drag and drop or selecting the import button) and the usual prompt experience occurs (different resolution/framerate asks user if they want to create new profile and continue to import, if it's the same resolution/framerate it imports with nothing extra)

### Additional context/output
Error output when I try to resolve the issue by clicking "Run Config Wizard" from the Settings tab.
* Missing package: AVFilter provides many effects. Install recommended
* Missing MLT module: avformat (FFmpeg) required for audio/video

### System details
**Windows version:** 10.0.19044 (Build 19044)

**OS architecture:** 64bit

**PowerShell version:** 5.1 (Build 19041, Revision 1682)

#### Scoop Configuration

```json
{
    "lastUpdate":  "2022-08-02T02:21:10.3356450+10:00",
    "SCOOP_REPO":  "https://github.com/ScoopInstaller/Scoop",
    "SCOOP_BRANCH":  "master"
}
```

**Comment by StarsbySea** [comment] 2023-05-06 14:18
I can't reproduce it in my environment, the current version is 23.04.0, please consider closing the issue if the problem has been solved.

**Comment by aliesbelik** [comment] 2024-06-10 03:58
Not reproducible with the latest version (`23.08.5`), both libraries available (`avfilter-9.dll`, `avformat-60.dll`).

**Closed by aliesbelik** 2024-06-10 03:58 UTC
Labels: bug
