### ISSUE TITLE
[Request]: Add VeraCrypt

### ISSUE THREAD

**Issue by sbstn87** [ScoopInstaller/Extras#11208] opened 2023-05-03 09:34 UTC
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

VeraCrypt

### Description

VeraCrypt is a free open source disk encryption software for Windows, Mac OSX and Linux.

### Homepage

https://veracrypt.fr/en/Home.html

### Download Link(s)

https://veracrypt.fr/en/Downloads.html

### Some Indication of Popularity/Repute

https://alternativeto.net/software/veracrypt/about/

**Comment by Lutra-Fs** [comment] 2023-05-03 14:49
duplicate of #2381

**Closed** 2023-05-04 06:06 UTC
Labels: package-request
