### ISSUE TITLE
[Bug] Avidemux2.8.1 - 7zip decompress error

### ISSUE THREAD

**Issue by Lifell** [ScoopInstaller/Extras#10782] opened 2023-03-16 19:53 UTC
Using the command "scoop install avidemux" downloads a 38.1 MB file called "dl.7z" that can't be opened. It's probably corrupted somehow? I don't know if this is something on my PC being borked. Deleting everything in the "cache" folder at "C:\Applications\Scoop\cache" doesn't fix it either.

```
PS C:\Windows\system32> scoop install avidemux
Installing 'avidemux' (2.8.1) [64bit] from extras bucket
Loading Avidemux_2.8.1.VC++.64bits.exe from cache
Checking hash of Avidemux_2.8.1.VC++.64bits.exe ... ok.
Extracting dl.7z ... ERROR Exit code was 2!
Failed to extract files from C:\Applications\Scoop\apps\avidemux\2.8.1\dl.7z.
Log file:
  C:\Applications\Scoop\apps\avidemux\2.8.1\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=avidemux%402.8.1%3a+decompress+error
```

```
7-Zip 22.01 (x64) : Copyright (c) 1999-2022 Igor Pavlov : 2022-07-15

Scanning the drive for archives:
1 file, 39995334 bytes (39 MiB)

Extracting archive: C:\Applications\Scoop\apps\avidemux\2.8.1\dl.7z

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
ERROR: C:\Applications\Scoop\apps\avidemux\2.8.1\dl.7z
C:\Applications\Scoop\apps\avidemux\2.8.1\dl.7z
Open ERROR: Cannot open the file as [7z] archive


ERRORS:
Is not archive
```

**Comment by Lifell** [comment] 2023-03-16 20:00
Well, seems "dl.7z" is actually an executable file that is being renamed during the package installation? I renamed the file so it has a .exe extension and it opens as the normal installer. So I'm guessing something is going wrong there.

![image](https://user-images.githubusercontent.com/26024918/225739160-5076b32b-43ed-4abf-9274-d973d7e673ac.png)

**Comment by HUMORCE** [comment] 2023-03-17 20:27
Duplicate of #9689

**Closed by HUMORCE** 2023-03-17 20:27 UTC
