### ISSUE TITLE
windows-terminal: function issue

### ISSUE THREAD

**Issue by ZvonimirSun** [ScoopInstaller/Extras#4531] opened 2020-08-04 01:28 UTC
As you can see, the shim cmd window will not close itself until the main windows terminal window is closed.

![image](https://user-images.githubusercontent.com/22871764/89242557-6f2bb400-d634-11ea-8209-7d2ca76abfe4.png)

**Comment by gitolicious** [comment] 2020-08-14 19:56
This is not related to windows-terminal but to scoop shims in general. I would call it a duplicate of https://github.com/lukesampson/scoop/issues/1606

**Closed** 2021-11-29 06:03 UTC
Labels: question
