### ISSUE TITLE
avidemux@2.8.1: decompress error

### ISSUE THREAD

**Issue by 26442566** [ScoopInstaller/Extras#10149] opened 2022-12-31 09:51 UTC
Failed to extract files from C:\Users\tb\scoop\apps\avidemux\2.8.1\dl.7z.
Log file:
  ~\scoop\apps\avidemux\2.8.1\7zip.log

`7zip.log`
```
7-Zip 22.01 (x64) : Copyright (c) 1999-2022 Igor Pavlov : 2022-07-15

Scanning the drive for archives:
1 file, 39995334 bytes (39 MiB)

Extracting archive: C:\Users\tb\scoop\apps\avidemux\2.8.1\dl.7z

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
ERROR: C:\Users\tb\scoop\apps\avidemux\2.8.1\dl.7z
C:\Users\tb\scoop\apps\avidemux\2.8.1\dl.7z
Open ERROR: Cannot open the file as [7z] archive


ERRORS:
Is not archive
```

**Comment by HUMORCE** [comment] 2022-12-31 11:17
Duplicate of #9689

**Closed by HUMORCE** 2022-12-31 11:17 UTC
